### ISSUE TITLE
Adding Model Loaders?

### ISSUE THREAD

**Issue by johnmastri** [JordanDelcros/npm-three-js#1]
Hey there - how would you go about adding in modules for Loaders?  I've tried a few things but no luck =/

Thanks!

**Comment by JordanDelcros** [comment]
Which loaders ? Json ? obj ?

**Comment by JordanDelcros** [comment]
I just added OBJ MTL and DDS loaders, you can look at them if you want to add more.

**Comment by johnmastri** [comment]
Thanks - working well!
