### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by bbdumdum** [JordanDelcros/npm-three-js#3]
Hi, 

I do not seem to be able to use addons when building with browserify. This is either not supported or I am simply missing the correct browserify settings to do this :)

When building a module that has three-js dependency, the resulting bundle file does not include the addon. In the browser, I am getting the error

```
bundle.js:1 Uncaught Error: Cannot find module './addons/CopyShader.js'
```

My javascript source is:

``` javascript
var THREE = require("three-js")(["CopyShader"])
```

I can provide an example project demonstrating this.

Thanks for any advice!

**Comment by JordanDelcros** [comment]
Arf... I'm not sure but almost 90% certain that is due to relative paths... Let me check that.

**Comment by JordanDelcros** [comment]
Ok... I missed that, Browserify do not support dynamic `require()` so you have to require addons before.
@hootstheowl recently maked a [pull request](https://github.com/JordanDelcros/npm-three-js/pull/2#issue-159750669) that solve this problem.

Start by requesting your addon(s) and give it to the THREE importer:

``` javascript
var CopyShader = require("three-js/addons/CopyShader");
var AnotherShader = require("three-js/addons/AnotherShader");
var THREE = require([CopyShader, AnotherShader]);
```

**Comment by bbdumdum** [comment]
This works, thank you!
