### ISSUE TITLE
Outdated Three.js version

### ISSUE THREAD

**Issue by rbozan** [JordanDelcros/npm-three-js#4]

**Comment by adrianq** [comment]
Any plans to update this? Thanks!

**Comment by JordanDelcros** [comment]
The new version is build in ES6 so it should be easiest to import (but the script is not universal, I know...)

**Comment by ua4192** [comment]
Hi.

I see that this package is based on R79 of threejs.
I need to use some addons that are missing:
-ColladaLoader
- Sea3DExporter

I have been trying to encapsulate CooladaLoader but it doesn't work, it fails trying to load FileLoader which is missing an part of the core of R87 or R88.

COuld you please update the release to R88 or upload these missing addons?

Best regards

**Comment by JordanDelcros** [comment]
Hey!

Like mentioned on the readme, that package is deprecated in favor of the original repo that now supports ES6 import/export.

Unfortunatly, the repo do not provides the examples using ES6 syntax.
